### PR TITLE
Added npm-check-updates

### PR DESCRIPTION
**Pull request by NetOpWibby**
I just tested with a project I used `pnpm` with and no issues occurred.

### CODE REVIEW

**Comment by zkochan** [comment]
But it doesn't update `shrinkwrap.yaml`.
It would have to run `pnpm install` after changin `package.json`

**Comment by NetOpWibby** [comment]
Ah okay. Welp, I'll close this then.

**Comment by zkochan** [comment]
though I like the output of `ncu`. Maybe we could update the output of `pnpm outdated` to look similar

**Comment by NetOpWibby** [comment]
Yeah I'm a big fan of `ncu`!

**Pull request closed without merging**
